### ISSUE TITLE
Couldn't find way to generate file named 0.embedding

### ISSUE THREAD

**Issue by Garson-hu** [petecheng/Time2Graph#2]
Thank you for sharing the code, but I have a problem running it, When I run the code with the following command:
"python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500  --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable"
 I get an error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`

I found this problem in shapelet_utils.py, and I don't see any way to generate this file.

I will be appreciated if you will to help me!

**Comment by petecheng** [comment]
This problem may be caused by 1) directory scripts/cache not exist; 2) 'deepwalk 'command has not executed successfully. I think it would be probably the latter case, and I suggest that you can check whether deepwalk (line 329-338, shapelet_utils.py) has been correctly installed and executed.

**Comment by liuguiyangnwpu** [comment]
`deepwalk --input /root/code/paper/Time2Graph/scripts/cache/ucr-Earthquakes/0.edgelist --format weighted_ed
gelist --output /root/code/paper/Time2Graph/scripts/cache/ucr-Earthquakes/0.embeddings --representation-size 256
Traceback (most recent call last):
  File "/root/code/paper/Time2GraphPlus/.venv/bin/deepwalk", line 33, in <module>
    sys.exit(load_entry_point('deepwalk==1.0.3', 'console_scripts', 'deepwalk')())
  File "/root/code/paper/Time2GraphPlus/.venv/lib/python3.7/site-packages/deepwalk-1.0.3-py3.7.egg/deepwalk/__main__.py", line 162, in main
    process(args)
  File "/root/code/paper/Time2GraphPlus/.venv/lib/python3.7/site-packages/deepwalk-1.0.3-py3.7.egg/deepwalk/__main__.py", line 58, in process
    raise Exception("Unknown file format: '%s'.  Valid formats: 'adjlist', 'edgelist', 'mat'" % args.format)
Exception: Unknown file format: 'weighted_edgelist'.  Valid formats: 'adjlist', 'edgelist', 'mat'`

**Comment by petecheng** [comment]
Hi,

It is the issue on the version of deepwalk you choose. Please use the modified version: https://github.com/petecheng/weighted_deepwalk. 

See README docs in the repo for install and usage instructions.



-----原始邮件-----
发件人:GuiYang ***@***.***>
发送时间:2021-08-21 17:18:53 (星期六)
收件人: petecheng/Time2Graph ***@***.***>
抄送: "Ziqiang Cheng" ***@***.***>, Comment ***@***.***>
主题: Re: [petecheng/Time2Graph] Couldn't find way to generate file named 0.embedding (#2)






deepwalk --input /root/code/paper/Time2Graph/scripts/cache/ucr-Earthquakes/0.edgelist --format weighted_ed gelist --output /root/code/paper/Time2Graph/scripts/cache/ucr-Earthquakes/0.embeddings --representation-size 256 Traceback (most recent call last): File "/root/code/paper/Time2GraphPlus/.venv/bin/deepwalk", line 33, in <module> sys.exit(load_entry_point('deepwalk==1.0.3', 'console_scripts', 'deepwalk')()) File "/root/code/paper/Time2GraphPlus/.venv/lib/python3.7/site-packages/deepwalk-1.0.3-py3.7.egg/deepwalk/__main__.py", line 162, in main process(args) File "/root/code/paper/Time2GraphPlus/.venv/lib/python3.7/site-packages/deepwalk-1.0.3-py3.7.egg/deepwalk/__main__.py", line 58, in process raise Exception("Unknown file format: '%s'. Valid formats: 'adjlist', 'edgelist', 'mat'" % args.format) Exception: Unknown file format: 'weighted_edgelist'. Valid formats: 'adjlist', 'edgelist', 'mat'

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.






Best,

Ziqiang Cheng

College of Computer Science and Technology, Zhejiang University

***@***.***

**Comment by wyf-ACCEPT** [comment]
> This problem may be caused by 1) directory scripts/cache not exist; 2) 'deepwalk 'command has not executed successfully. I think it would be probably the latter case, and I suggest that you can check whether deepwalk (line 329-338, shapelet_utils.py) has been correctly installed and executed.

Same question. That's helps a lot 👍 :)

**Comment by YoungGalano** [comment]
> Thank you for sharing the code, but I have a problem running it, When I run the code with the following command: "python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500 --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable" I get an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`
> 
> I found this problem in shapelet_utils.py, and I don't see any way to generate this file.
> 
> I will be appreciated if you will to help me!

你解决了这个问题吗？我也遇到了，光看作者给的回复不太明白该怎么解决。

**Comment by Garson-hu** [comment]
> > Thank you for sharing the code, but I have a problem running it, When I run the code with the following command: "python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500 --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable" I get an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`
> > I found this problem in shapelet_utils.py, and I don't see any way to generate this file.
> > I will be appreciated if you will to help me!
> 
> 你解决了这个问题吗？我也遇到了，光看作者给的回复不太明白该怎么解决。

解决方案是需要使用作者仓库里面的 [weighted_deepwalk](https://github.com/petecheng/weighted_deepwalk). 而不是直接使用 deep_walk, 作者对 deep_walk 进行了修改, 换成了自己写的 weighted_deepwalk, 具体怎么安装作者在这个仓库的 readme 里面说的很详细, 照着步骤来就可以

**Comment by YoungGalano** [comment]
> > > Thank you for sharing the code, but I have a problem running it, When I run the code with the following command: "python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500 --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable" I get an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`
> > > I found this problem in shapelet_utils.py, and I don't see any way to generate this file.
> > > I will be appreciated if you will to help me!
> > 
> > 
> > 你解决了这个问题吗？我也遇到了，光看作者给的回复不太明白该怎么解决。
> 
> 解决方案是需要使用作者仓库里面的 [weighted_deepwalk](https://github.com/petecheng/weighted_deepwalk). 而不是直接使用 deep_walk, 作者对 deep_walk 进行了修改, 换成了自己写的 weighted_deepwalk, 具体怎么安装作者在这个仓库的 readme 里面说的很详细, 照着步骤来就可以

我确实是按照那个仓库里的readme装了weighted_deepwalk，但是问题并没有解决。有没有什么办法验证一下我安装的是否正确呢？
（我的步骤如下：1. 使用pip install deepwalk安装原始deepwalk。2. 下载那个仓库里的文件，并将__main__.py和weighted_random_walk.py文件放入Ubuntu\root\anaconda3\envs\Time2Graph\lib\python3.6\site-packages\deepwalk目录中，替换原有文件）

**Comment by Garson-hu** [comment]
> 
这样你只能在 shapelet_utils 这个文件中打断点慢慢debug了, 这个问题有点久了,细节上我也忘了, 记得应该更改了之后就可以正常run

**Comment by Garson-hu** [comment]
> > > > Thank you for sharing the code, but I have a problem running it, When I run the code with the following command: "python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500 --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable" I get an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`
> > > > I found this problem in shapelet_utils.py, and I don't see any way to generate this file.
> > > > I will be appreciated if you will to help me!
> > > 
> > > 
> > > 你解决了这个问题吗？我也遇到了，光看作者给的回复不太明白该怎么解决。
> > 
> > 
> > 解决方案是需要使用作者仓库里面的 [weighted_deepwalk](https://github.com/petecheng/weighted_deepwalk). 而不是直接使用 deep_walk, 作者对 deep_walk 进行了修改, 换成了自己写的 weighted_deepwalk, 具体怎么安装作者在这个仓库的 readme 里面说的很详细, 照着步骤来就可以
> 
> 我确实是按照那个仓库里的readme装了weighted_deepwalk，但是问题并没有解决。有没有什么办法验证一下我安装的是否正确呢？ （我的步骤如下：1. 使用pip install deepwalk安装原始deepwalk。2. 下载那个仓库里的文件，并将__main__.py和weighted_random_walk.py文件放入Ubuntu\root\anaconda3\envs\Time2Graph\lib\python3.6\site-packages\deepwalk目录中，替换原有文件）

这样你只能在 shapelet_utils 这个文件中打断点慢慢debug了, 这个问题有点久了,细节上我也忘了, 记得应该更改了之后就可以正常run

**Comment by YoungGalano** [comment]
> > > > > Thank you for sharing the code, but I have a problem running it, When I run the code with the following command: "python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500 --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable" I get an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`
> > > > > I found this problem in shapelet_utils.py, and I don't see any way to generate this file.
> > > > > I will be appreciated if you will to help me!
> > > > 
> > > > 
> > > > 你解决了这个问题吗？我也遇到了，光看作者给的回复不太明白该怎么解决。
> > > 
> > > 
> > > 解决方案是需要使用作者仓库里面的 [weighted_deepwalk](https://github.com/petecheng/weighted_deepwalk). 而不是直接使用 deep_walk, 作者对 deep_walk 进行了修改, 换成了自己写的 weighted_deepwalk, 具体怎么安装作者在这个仓库的 readme 里面说的很详细, 照着步骤来就可以
> > 
> > 
> > 我确实是按照那个仓库里的readme装了weighted_deepwalk，但是问题并没有解决。有没有什么办法验证一下我安装的是否正确呢？ （我的步骤如下：1. 使用pip install deepwalk安装原始deepwalk。2. 下载那个仓库里的文件，并将__main__.py和weighted_random_walk.py文件放入Ubuntu\root\anaconda3\envs\Time2Graph\lib\python3.6\site-packages\deepwalk目录中，替换原有文件）
> 
> 这样你只能在 shapelet_utils 这个文件中打断点慢慢debug了, 这个问题有点久了,细节上我也忘了, 记得应该更改了之后就可以正常run

好吧，我试试看。
谢谢！

**Comment by HengruiLou** [comment]
> > > > > > Thank you for sharing the code, but I have a problem running it, When I run the code with the following command: "python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500 --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable" I get an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`
> > > > > > I found this problem in shapelet_utils.py, and I don't see any way to generate this file.
> > > > > > I will be appreciated if you will to help me!
> > > > > 
> > > > > 
> > > > > 你解决了这个问题吗？我也遇到了，光看作者给的回复不太明白该怎么解决。
> > > > 
> > > > 
> > > > 解决方案是需要使用作者仓库里面的 [weighted_deepwalk](https://github.com/petecheng/weighted_deepwalk). 而不是直接使用 deep_walk, 作者对 deep_walk 进行了修改, 换成了自己写的 weighted_deepwalk, 具体怎么安装作者在这个仓库的 readme 里面说的很详细, 照着步骤来就可以
> > > 
> > > 
> > > 我确实是按照那个仓库里的readme装了weighted_deepwalk，但是问题并没有解决。有没有什么办法验证一下我安装的是否正确呢？ （我的步骤如下：1. 使用pip install deepwalk安装原始deepwalk。2. 下载那个仓库里的文件，并将__main__.py和weighted_random_walk.py文件放入Ubuntu\root\anaconda3\envs\Time2Graph\lib\python3.6\site-packages\deepwalk目录中，替换原有文件）
> > 
> > 
> > 这样你只能在 shapelet_utils 这个文件中打断点慢慢debug了, 这个问题有点久了,细节上我也忘了, 记得应该更改了之后就可以正常run
> 
> 好吧，我试试看。 谢谢！

你好，我按照此问题的处理方式进行操作后遇到了和您一样的问题，请问您后续解决此问题了吗？

**Comment by YoungGalano** [comment]
> > > > > > > Thank you for sharing the code, but I have a problem running it, When I run the code with the following command: "python scripts/run.py --dataset ucr-Earthquakes --K 50 --C 500 --num_segment 21 --seg_length 24 --data_size 1 --embed concate --percentile 5 --gpu_enable" I get an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/internship/code/Time2Graph/scripts/cache/ucr-Earthquakes//0.embeddings'`
> > > > > > > I found this problem in shapelet_utils.py, and I don't see any way to generate this file.
> > > > > > > I will be appreciated if you will to help me!
> > > > > > 
> > > > > > 
> > > > > > 你解决了这个问题吗？我也遇到了，光看作者给的回复不太明白该怎么解决。
> > > > > 
> > > > > 
> > > > > 解决方案是需要使用作者仓库里面的 [weighted_deepwalk](https://github.com/petecheng/weighted_deepwalk). 而不是直接使用 deep_walk, 作者对 deep_walk 进行了修改, 换成了自己写的 weighted_deepwalk, 具体怎么安装作者在这个仓库的 readme 里面说的很详细, 照着步骤来就可以
> > > > 
> > > > 
> > > > 我确实是按照那个仓库里的readme装了weighted_deepwalk，但是问题并没有解决。有没有什么办法验证一下我安装的是否正确呢？ （我的步骤如下：1. 使用pip install deepwalk安装原始deepwalk。2. 下载那个仓库里的文件，并将__main__.py和weighted_random_walk.py文件放入Ubuntu\root\anaconda3\envs\Time2Graph\lib\python3.6\site-packages\deepwalk目录中，替换原有文件）
> > > 
> > > 
> > > 这样你只能在 shapelet_utils 这个文件中打断点慢慢debug了, 这个问题有点久了,细节上我也忘了, 记得应该更改了之后就可以正常run
> > 
> > 
> > 好吧，我试试看。 谢谢！
> 
> 你好，我按照此问题的处理方式进行操作后遇到了和您一样的问题，请问您后续解决此问题了吗？

不好意思，过去有点太久了，所以我也记不清当时具体是如何解决的了
